### PR TITLE
Add GitHub action for build and test

### LINKED ISSUE #58: Add github actions for build & test
+ add it as a pull request requirements

### PR DESCRIPTION
**Pull request by TomasKypta**
Fix #58

### CODE REVIEW

**Review by kober32 — COMMENTED** [review]
Do we really want to run in on [self hosted]? I'm trying to avoid it as much as possible and slowly porting older projects to azure/hosted runner

**Comment by hvge** [comment]
I recommend you to upgrade to PA-SDK to 1.7.8

**Comment by TomasKypta** [comment]
Update to the newest PA is going to happen in a separate PR. There are more thing to update than that.

**Review by kober32 — APPROVED** [review]
Looks OK

**Pull request merged**
